Noteboo to check that the spec is compatible with NetwrokX

In [29]:
import networkx as nx
import json as js
import pandas as pd
import csv
from numpy import NaN
import numpy

In [2]:
data = pd.read_csv("exampleEdgelist.csv")
data

#Node1 node2  weight
0      A     B     0.1
1      C     D     0.3

In [3]:
g1 = nx.read_weighted_edgelist("exampleEdgelist.csv", delimiter=',')

In [4]:
print(g1.edges())
g1.nodes()

[('A', 'B'), ('C', 'D')]


NodeView(('A', 'B', 'C', 'D'))

In [5]:
g1.get_edge_data('A',"B")

g1.get_edge_data("C","D")

{'weight': 0.3}

In [31]:
### convert the graph to a numpy array

array1 = nx.to_numpy_array(g1)
array1

array([[0. , 0.1, 0. , 0. ],
       [0.1, 0. , 0. , 0. ],
       [0. , 0. , 0. , 0.3],
       [0. , 0. , 0.3, 0. ]])

In [38]:
###Try a more complicated edgelist, so try with a new edgelist with missisng values

with open("singleEdgelis.csv",'w') as new_file:
    
    csv_writer = csv.writer(new_file, delimiter = ',')
    
    csv_writer.writerow([1,2,3])
    csv_writer.writerow([2,3,NaN])
    csv_writer.writerow([3,4,5])


In [55]:
data2 = pd.read_csv("singleEdgelis.csv")
data2

1  2    3
0  2  3  NaN
1  3  4  5.0

In [39]:
g2 = nx.read_weighted_edgelist("singleEdgelis.csv", delimiter=',')
print(g2.edges())
g2.nodes()

[('1', '2'), ('2', '3'), ('3', '4')]


NodeView(('1', '2', '3', '4'))

In [40]:
print(g2.get_edge_data('2',"3"))

g2.get_edge_data("3","4")

{'weight': nan}


{'weight': 5.0}

In [41]:
##convert to numpy array

array2 = nx.to_numpy_array(g2)
array2


array([[0., 3., 0., 0.],
       [3., 0., 0., 0.],
       [0., 0., 0., 5.],
       [0., 0., 5., 0.]])

### Create a multigraph csv

In [9]:
with open("multiEdgelist.csv",'w') as new_file:
    
    csv_writer = csv.writer(new_file, delimiter = ',')
    
    csv_writer.writerow([1,2,3,6])
    csv_writer.writerow([2,3,8,7])
    csv_writer.writerow([3,4,5,8])

In [57]:
data3 = pd.read_csv("multiEdgelist.csv", header = None)
data3

0  1  2  3
0  1  2  3  6
1  2  3  8  7
2  3  4  5  8

In [10]:
g3 = nx.read_edgelist("multiEdgelist.csv", delimiter=',', data=(('eweight',float),('gweight', float)))
g3

In [11]:
print(g3.edges)
g3.nodes

[('1', '2'), ('2', '3'), ('3', '4')]


NodeView(('1', '2', '3', '4'))

In [12]:

g3.get_edge_data("3","4")

{'eweight': 5.0, 'gweight': 8.0}

In [46]:
array3 = nx.to_numpy_array(g3, weight='eweight') ##can make an array with one type of weight
array3

array([[0., 3., 0., 0.],
       [3., 0., 8., 0.],
       [0., 8., 0., 5.],
       [0., 0., 5., 0.]])

In [48]:
array3b = nx.to_numpy_array(g3,weight='gweight')### can make an array with the other type of weight
array3b

array([[0., 6., 0., 0.],
       [6., 0., 7., 0.],
       [0., 7., 0., 8.],
       [0., 0., 8., 0.]])

### Trial of multiweight graph with None 

In [24]:
with open("multiEdgelistNone.csv",'w') as new_file:
    
    csv_writer = csv.writer(new_file, delimiter = ',')
    
    csv_writer.writerow([1,2,3,6,9])
    csv_writer.writerow([2,3,8,7,NaN])
    csv_writer.writerow([3,4,5,NaN,8])

In [58]:
data4 = pd.read_csv("multiEdgelistNone.csv", header = None)
data4

0  1  2    3    4
0  1  2  3  6.0  9.0
1  2  3  8  7.0  NaN
2  3  4  5  NaN  8.0

In [26]:
g4 = nx.read_edgelist("multiEdgelistNone.csv", delimiter=',', data=(('eweight',float),('gweight', float),("fweight", float)))
g4.get_edge_data("3","4")

{'eweight': 5.0, 'gweight': nan, 'fweight': 8.0}

In [53]:
G4 = nx.MultiGraph(g4)
array4 = nx.to_numpy_array(G4, weight = 'fweight')
array4

array([[0., 9., 0., 0.],
       [9., 0., 0., 0.],
       [0., 0., 0., 8.],
       [0., 0., 8., 0.]])

### trial to check how graphml files are read in netwrokx

In [60]:
gml = nx.read_graphml("./data/c.elegans.herm_pharynx_1.graphml")
gml.edges() ## read the egdes correctly but what about the weights?
 

OutMultiEdgeDataView([('n0', 'n1'), ('n0', 'n4'), ('n0', 'n12'), ('n0', 'n13'), ('n0', 'n43'), ('n0', 'n54'), ('n0', 'n55'), ('n0', 'n56'), ('n0', 'n57'), ('n0', 'n58'), ('n0', 'n59'), ('n0', 'n67'), ('n0', 'n111'), ('n0', 'n158'), ('n0', 'n168'), ('n0', 'n169'), ('n0', 'n176'), ('n0', 'n178'), ('n0', 'n224'), ('n1', 'n0'), ('n1', 'n5'), ('n1', 'n12'), ('n1', 'n13'), ('n1', 'n44'), ('n1', 'n53'), ('n1', 'n55'), ('n1', 'n56'), ('n1', 'n57'), ('n1', 'n59'), ('n1', 'n66'), ('n1', 'n159'), ('n1', 'n168'), ('n1', 'n177'), ('n1', 'n179'), ('n1', 'n183'), ('n1', 'n223'), ('n2', 'n0'), ('n2', 'n3'), ('n2', 'n16'), ('n2', 'n53'), ('n2', 'n54'), ('n2', 'n59'), ('n2', 'n69'), ('n2', 'n70'), ('n2', 'n80'), ('n2', 'n82'), ('n2', 'n110'), ('n2', 'n116'), ('n2', 'n122'), ('n2', 'n128'), ('n2', 'n164'), ('n2', 'n171'), ('n2', 'n173'), ('n2', 'n174'), ('n2', 'n175'), ('n2', 'n182'), ('n2', 'n183'), ('n2', 'n186'), ('n2', 'n196'), ('n2', 'n198'), ('n2', 'n210'), ('n2', 'n214'), ('n2', 'n218'), ('n2', 'n

In [61]:
gml.nodes

NodeView(('n0', 'n1', 'n2', 'n3', 'n4', 'n5', 'n6', 'n7', 'n8', 'n9', 'n10', 'n11', 'n12', 'n13', 'n14', 'n15', 'n16', 'n17', 'n18', 'n19', 'n20', 'n21', 'n22', 'n23', 'n24', 'n25', 'n26', 'n27', 'n28', 'n29', 'n30', 'n31', 'n32', 'n33', 'n34', 'n35', 'n36', 'n37', 'n38', 'n39', 'n40', 'n41', 'n42', 'n43', 'n44', 'n45', 'n46', 'n47', 'n48', 'n49', 'n50', 'n51', 'n52', 'n53', 'n54', 'n55', 'n56', 'n57', 'n58', 'n59', 'n60', 'n61', 'n62', 'n63', 'n64', 'n65', 'n66', 'n67', 'n68', 'n69', 'n70', 'n71', 'n72', 'n73', 'n74', 'n75', 'n76', 'n77', 'n78', 'n79', 'n80', 'n81', 'n82', 'n83', 'n84', 'n85', 'n86', 'n87', 'n88', 'n89', 'n90', 'n91', 'n92', 'n93', 'n94', 'n95', 'n96', 'n97', 'n98', 'n99', 'n100', 'n101', 'n102', 'n103', 'n104', 'n105', 'n106', 'n107', 'n108', 'n109', 'n110', 'n111', 'n112', 'n113', 'n114', 'n115', 'n116', 'n117', 'n118', 'n119', 'n120', 'n121', 'n122', 'n123', 'n124', 'n125', 'n126', 'n127', 'n128', 'n129', 'n130', 'n131', 'n132', 'n133', 'n134', 'n135', 'n136', 'n13

In [62]:
gml.get_edge_data('n0',"n1")

{0: {'synapse_type': 'E', 'weight': 1.0}}

In [66]:
array5 = nx.to_numpy_array(gml)
array5

array([[0., 1., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])